mcrblg/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "articles#index"

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: {:new => ''}
  resources :articles do
    resources :comments
  end

end

mcrblg/app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :text, presence: true
  has_many :comments
  belongs_to :user

  def subject
    title
  end

  def last_comment
    comments.last
  end

end

mcrblg/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

mcrblg/app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :message, presence: true
end

mcrblg/app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :username
  validates_uniqueness_of :username
end

mcrblg/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

mcrblg/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :only =>[:new, :create]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)

    if @article.valid?
      @article.save
      redirect_to @article
    else
      render action: 'new'
    end

  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :user_id).merge(user_id: current_user.id)
  end

end

mcrblg/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :only =>[:create]

  def create
    @article = Article.find(params[:article_id])
    @article.comments.create({user_id: current_user.id, body: params[:comment]['body'] })

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

mcrblg/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end

  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

mcrblg/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms

  end

  def about

  end

end

mcrblg/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

mcrblg/app/helpers/application_helper.rb
module ApplicationHelper
end

mcrblg/app/helpers/articles_helper.rb
module ArticlesHelper
end

mcrblg/app/helpers/comments_helper.rb
module CommentsHelper
end

mcrblg/app/helpers/contacts_helper.rb
module ContactsHelper
end

mcrblg/app/helpers/pages_helper.rb
module PagesHelper
end

mcrblg/app/helpers/welcome_helper.rb
module WelcomeHelper
end

mcrblg/app/views/articles/index.html.erb
<% @articles.each do |art| %>

  <p>
    <b><%= link_to art.title, article_path(art)%></b>
  </p>


  <p>
    <%= art.text %>
  </p>
  <p>

    Author: <%= art.user.username%> |
    <%= art.created_at.strftime("%Y-%m-%d")%> |

    <%= link_to "Comments: #{art.comments.length}", article_path(art)%>
  </p>
  <hr />

<% end%>

mcrblg/app/views/articles/new.html.erb
<h3>New Article</h3>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </p>

  <p>
    <%= f.label :text %> <br />
    <%= f.text_area :text, :class => "form-control", :rows => "5" %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

mcrblg/app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<p>
  <%= @article.text %>
</p>
<hr />
<p>

<b>Comments:</b>
</p>

<% @article.comments.each do |comm|%>
  <p>
    <%= comm.user.username %> said:
  </p>
  <p>
    <i><%= comm.body %></i>
  </p>
  <hr />
<% end%>

<p>
  <i>Send comment</i>
</p>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.text_area :body, :class => "form-control", :rows => "5"  %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

mcrblg/app/views/contacts/create.html.erb
<p>
  Done!
</p>

mcrblg/app/views/contacts/new.html.erb
<h3><%= t('contacts.contact_us') %></h3>
<%= form_for :contact, url: contacts_path do |f| %>
  <% if @contact && @contact.errors.any? %>
    <p>
      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end%>
      </ul>

    </p>
  <% end %>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :message %> <br />
    <%= f.text_area :message %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

mcrblg/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mcrblg</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="style.css" />
  <script src="script.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-static-top">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <div class="navbar-brand">MCRBLG!</div>
       </div>
       <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav">
           <li class="active"><%= link_to 'Articles', articles_path %></li>
           <li><%= link_to 'New article', new_article_path %></li>
         </ul>
         <ul class="nav navbar-nav navbar-right">
           <li class="notice">
             <%= notice %>
           </li>
           <li class="alert">
             <%= alert %>
           </li>
           <% if user_signed_in? %>

            <li>
               <div class="navbar-text">Hello, <%= current_user.username %></div>
            </li>
            <li>
                 <%= link_to 'Sign Out!', destroy_user_session_path, method: :delete %>
            </li>
            <% else %>
             <li>
               <%= link_to 'Sign In!', new_user_session_path %>
           </li>
           <% end %>
         </ul>
       </div><!--/.nav-collapse -->
     </div>
   </nav>

  <div class="container">
    <p class="notice"></p>
    <p class="alert"></p>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

mcrblg/app/views/pages/about.html.erb
<h3>Ololo</h3>

mcrblg/app/views/pages/terms.html.erb
<h3>No terms =)</h3>

mcrblg/app/views/welcome/index.html.erb
<h1>Ololo</h1>